
package com.proyecto.view;

import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author aspxe
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrueba
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInformacion = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuGenerar = new javax.swing.JMenu();
        itemQr = new javax.swing.JMenuItem();
        menuFunciones = new javax.swing.JMenu();
        itemBD = new javax.swing.JMenuItem();
        itemAsistencias = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 480));

        javax.swing.GroupLayout panelInformacionLayout = new javax.swing.GroupLayout(panelInformacion);
        panelInformacion.setLayout(panelInformacionLayout);
        panelInformacionLayout.setHorizontalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        panelInformacionLayout.setVerticalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );

        menuGenerar.setText("Generar");

        itemQr.setText("Qr's");
        itemQr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemQrActionPerformed(evt);
            }
        });
        menuGenerar.add(itemQr);

        jMenuBar1.add(menuGenerar);

        menuFunciones.setText("Funciones");

        itemBD.setText("Cargar Base de Datos");
        itemBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBDActionPerformed(evt);
            }
        });
        menuFunciones.add(itemBD);

        itemAsistencias.setText("Tomar Asistencias");
        itemAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAsistenciasActionPerformed(evt);
            }
        });
        menuFunciones.add(itemAsistencias);

        jMenuBar1.add(menuFunciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showPanel(JPanel panel){
        panel.setSize(900,480);
        panel.setLocation(0,0);
        panelInformacion.removeAll();
        panelInformacion.add(panel, BorderLayout.CENTER);
        panelInformacion.revalidate();
        panelInformacion.repaint();
    }
    
    private void itemQrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemQrActionPerformed
        
        GenerarQrs panel = new GenerarQrs();
        showPanel(panel);
        System.out.println(panel.toString());
    }//GEN-LAST:event_itemQrActionPerformed

    private void itemBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBDActionPerformed
        
        CargarBD panel = new CargarBD();
        showPanel(panel);
        
    }//GEN-LAST:event_itemBDActionPerformed

    private void itemAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAsistenciasActionPerformed
        Asistencias panel = null;
        try {
            panel = new Asistencias();
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        showPanel(panel);
    }//GEN-LAST:event_itemAsistenciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAsistencias;
    private javax.swing.JMenuItem itemBD;
    private javax.swing.JMenuItem itemQr;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuFunciones;
    private javax.swing.JMenu menuGenerar;
    private javax.swing.JPanel panelInformacion;
    // End of variables declaration//GEN-END:variables
}
